{% set version = "1.7.2" %}

package:
  name: beaker-py
  version: {{ version }}

source:
  url: https://github.com/allenai/beaker-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 21c670c76dd0b5b984c8da5f3872fec912c5ba1b897c1e500a663c2077dbd518

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - docker-py >=5.0,<7
    - packaging
    - pydantic >=1.8.2,<1.11
    - pyyaml
    - requests
    - rich >=12.3,<12.6

test:
  requires:
    - pip
    # - pytest
    - python {{ python_min }}
  imports:
    - beaker
  # basically all tests require a token we don't have. Perhaps
  # we'll get a special setup accommodated by upstream, see
  # https://github.com/conda-forge/staged-recipes/pull/19771#issuecomment-1194356768
  # source_files:
  #   - tests/
  #   - test_fixtures/
  commands:
    - pip check
    # - pytest -v tests/

about:
  home: https://github.com/allenai/beaker-py
  license: Apache-2.0
  license_file: LICENSE
  summary: A Beaker client for Python
  dev_url: https://github.com/allenai/beaker-py

extra:
  recipe-maintainers:
    - h-vetinari
